### ISSUE TITLE
Plugin unable parse message and suppressed

### ISSUE THREAD

**Issue by hiepsikhokhao** [fangli/fluent-plugin-influxdb#32] opened 2015-12-01 03:25 UTC
Dear fangli,

Today i view td-agent log and see error log: unable to parse...   . I sure my format of message's correct, But plugin say unable to parse ( miss "," between "ran=408880 ssec=1448935558" ). And buffer stuck this error message cannot retry (because of error) or by pass error message when i restart td-agent. I must delete buffer. Please check & fix it  

P/s: I ran td-agent with influxdb-plugin in 3 days but today it error. I delete buffer & restart , td-agent work back
 
2015-12-01 10:13:03 +0700 [warn]: temporarily failed to flush the buffer. next_retry=2015-12-01 10:34:00 +0700 error_class="InfluxDB::Error" error="unable to parse 'cdn.stream1.mecloud.vn,node=mc11,schema=http,domain=cdn.stream1.mecloud.vn,uri=/clip/2015/12/1/8/19/77050ecf7bccc5338afb810797050cd6_360.mp4,status=206,cache=HIT,ip=113.162.174.190,nation=VN,region=Ho\\ Chi\\ Minh,agent=GET\\ /clip/2015/12/1/8/19/77050ecf7bccc5338afb810797050cd6_360.mp4?e=1448949944&s=8y0vl3kSYUgw7jkY-sXqAw\\ HTTP/1.1,ran=408880 ssec=1448935558,byte=1188298,ust=0,usl=0,hit=1,xx2=1,xx3=0,xx4=0,xx5=0,byteos=0,bytevn=1188298,req=1,reqvn=1,reqos=0 1448935558': missing tag value\n" plugin_id="object:3feac88730c8"
  2015-12-01 10:13:03 +0700 [warn]: suppressed same stacktrace

**Comment by repeatedly** [comment] 2015-12-01 04:57
Please paste your configuration.

**Comment by hiepsikhokhao** [comment] 2015-12-02 04:20
Hi @repeatedly , 

I used many plugins. Configuration for influxdb plugin's bottom. Thanks 

P/s: Today i have error again.
Origin message : {"node":"mc21","ssec":1449022064,"schema":"http","domain":"cdn.stream1.mecloud.vn","uri":"/clip/2015/12/1/17/14/ed1965e7850c86dc5854b876b0c4425a_360.mp4","status":"200","byte":1067621,"cache":"HIT","ip":"71.95.193.239","nation":"US","region":"California","ust":0,"usl":0,"agent":"Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0;WUID=FDED3444AE0247E0AAB512F03CB66A21;WTB=28363) like Gecko","hit":1,"ran":40036,"xx2":1,"xx3":0,"xx4":0,"xx5":0,"byteos":1067621,"bytevn":0,"req":1,"reqvn":0,"reqos":1}

Error: 2015-12-02 09:49:20 +0700 [warn]: suppressed same stacktrace
2015-12-02 10:34:43 +0700 [warn]: temporarily failed to flush the buffer. next_retry=2015-12-02 12:04:13 +0700 error_class="InfluxDB::Error" error="unable to parse 'cdn.stream1.mecloud.vn,node=mc21,schema=http,domain=cdn.stream1.mecloud.vn,uri=/clip/2015/12/1/17/14/ed1965e7850c86dc5854b876b0c4425a_360.mp4,status=200,cache=HIT,ip=71.95.193.239,nation=US,region=California,agent=Mozilla/5.0\\ (Windows\\ NT\\ 10.0;\\ WOW64;\\ Trident/7.0;\\ rv:11.0;WUID=FDED3444AE0247E0AAB512F03CB66A21;WTB=28363)\\ like\\ Gecko,ran=40036 ssec=1449022064,byte=1067621,ust=0,usl=0,hit=1,xx2=1,xx3=0,xx4=0,xx5=0,byteos=1067621,bytevn=0,req=1,reqvn=0,reqos=1 1449022064': missing tag value\n" plugin_id="object:3fc32b28c55c" 
 


---- Configuartion ----
root@MC-STR1-226 ~ $ cat /etc/td-agent/td-agent.conf
<source>
  type forward
  bind 0.0.0.0
  port 24224
</source>

# Scribe output
<match cdn.l.**>
  type random
  add_tag_prefix r.
  integer 0..1000000
  field ran
</match>

<match r.cdn.l.**>
  type rewrite_tag_filter
  capitalize_regex_backreference yes
  rewriterule1 status ^2    2.${tag}
  rewriterule2 status ^3    3.${tag}
  rewriterule3 status ^4    4.${tag}
  rewriterule4 status ^5    5.${tag}
</match>

<match 2.r.cdn.l.**>
  type record_reformer
  renew_record false
  enable_ruby false
  tag s.${tag_suffix[4]}

  <record>
    xx2 1
    xx3 0
    xx4 0
    xx5 0
  </record>
</match>

<match 3.r.cdn.l.**>
  type record_reformer
  renew_record false
  enable_ruby false
  tag s.${tag_suffix[4]}

  <record>
    xx2 0
    xx3 1
    xx4 0
    xx5 0
  </record>
</match>

<match 4.r.cdn.l.**>
  type record_reformer
  renew_record false
  enable_ruby false
  tag s.${tag_suffix[4]}

  <record>
    xx2 0
    xx3 0
    xx4 1
    xx5 0
  </record>
</match>

<match 5.r.cdn.l.**>
  type record_reformer
  renew_record false
  enable_ruby false
  tag s.${tag_suffix[4]}

  <record>
    xx2 0
    xx3 0
    xx4 0
    xx5 1
  </record>
</match>

<match s.**>
  type rewrite_tag_filter
  capitalize_regex_backreference yes
  rewriterule1 nation VN    vn.${tag}
  rewriterule2 nation !VN   os.${tag}
</match>

<match vn.s.**>
  type record_reformer
  renew_record false
  remove_keys root
  enable_ruby false
  tag na.${tag_suffix[2]}

  <record>
    byteos 0
    bytevn ${byte}
    req 1
    reqvn 1
    reqos 0
  </record>
</match>

<match os.s.**>
  type record_reformer
  renew_record false
  remove_keys root
  enable_ruby false
  tag na.${tag_suffix[2]}
  <record>
    byteos ${byte}
    bytevn 0
    req 1
    reqvn 0
    reqos 1
  </record>
</match>

<match na.**>
  type typecast
  item_types byte:integer,ust:integer,usl:integer,hit:integer,bytevn:integer,byteos:integer,req:integer,reqvn:integer,reqos:integer,xx2:integer,xx3:integer,xx4:integer,xx5:integer,ssec:integer
  prefix ty
</match>

<match ty.na.**>
  type copy
  <store>
    type scribe
    host 127.0.0.1
    port 1563
    #port 2563
    field_ref message
    format_to_json yes
    remove_prefix ty.na

    # buffer
    buffer_type file
    buffer_path /etc/td-agent/scribe_buffer/scribe
    buffer_chunk_limit 32m
    buffer_queue_limit 256
    flush_interval 3s
    retry_wait 20s
    num_threads 8
  </store>

  <store>
    type influxdb
    log_level debug
    host  localhost
    port  8086
    dbname cdn_raw_log
    user  mecdn
    password  mecdn@2015
    use_ssl false
    time_precision s
    remove_tag_prefix ty.na.
    tag_keys ["node", "status", "domain", "cache", "ran", "uri", "nation", "agent", "ip", "schema", "region"]

    #buffer
    buffer_type file
    buffer_path /etc/td-agent/influxdb_buffer/influxdb
    buffer_chunk_limit 32m
    buffer_queue_limit 1024
    disable_retry_limit true
    flush_interval 3s
    retry_wait 20s
    max_retry_wait 24h
    num_threads 8
  </store>
</match>

**Comment by repeatedly** [comment] 2015-12-02 08:35
I removed `agent` from `tag_keys` and it worked.
`agent` seems to contain invalid character for influxdb tags.
I will check it deeply later.

**Comment by repeatedly** [comment] 2015-12-02 08:48
I found the cause and one user has already sent a patch to influxdb-ruby.

https://github.com/influxdb/influxdb-ruby/pull/119

After release new version including above patch, this problem should be fixed.

**Comment by hiepsikhokhao** [comment] 2015-12-02 09:37
Hi @repeatedly ,

I update patch & it works. Great
 
Thank you so much.

**Closed** 2015-12-04 17:43 UTC
